---
dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - 3.8

env:
  matrix:
    - SQLALCHEMY="~=1.3.5" WTFORMS="<3"
    - SQLALCHEMY="~=1.2.9" WTFORMS="<3"
    - SQLALCHEMY="" WTFORMS="<3"
    - SQLALCHEMY="~=1.3.5" WTFORMS=">=3.0.0a1"
    - SQLALCHEMY="~=1.2.9" WTFORMS=">=3.0.0a1"
    - SQLALCHEMY=">=1.4.0b1" WTFORMS=">=3.0.0a1"
    - SQLALCHEMY="" WTFORMS=">=3.0.0a1"


# command to install dependencies
install:
  - "pip install WTForms$WTFORMS SQLAlchemy$SQLALCHEMY"
  - "pip install ."
  - "pip install -r tests/requirements.txt"

# command to run tests
script: coverage run setup.py test
after_success:
  - pip install coveralls
  - coveralls
